---
### Ваш токен
token: abcd
### Айди группы
group: 1234
### Режим отладки
debug: false
### Текст поста. %name% заменяется на имя игрока , %group% на привилегию
text: "Игрок %name% получил привилегию %group%"
...
